Feat/#129 market ranking 시스템 도입
Eagle2gle/wealth-marble-backend pull request #130
Opened 2023-02-25 14:01 UTC by CEOJINSUNG

## 💬 Issue Number

> closes #129

## 🤷‍♂️ Description

> 작업 내용에 대한 설명

- [] : 체크리스트
- [] : 체크리스트
- [] : 체크리스트

## 📋 Check List

> PR 전 체크해주세요.

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] PR 내용이 정상 동작한다는 것을 보증하는 **테스트**를 추가하였는가?

## 📒 Remarks

> 팀원이 코드리뷰 시 주의할 점 또는 말하고 싶은 점 특이사항

- 레디스 로컬에서 실행하기 : https://hays99.tistory.com/262
- 레디스 랭킹 도입하기 : https://cantcoding.tistory.com/82

2023-02-25 16:19 UTC, NaayoungKwon requested changes
redis연결하고 제가 작성한 부분까지 추가하느라 고생많으셨습니다.
아래 코멘트 단 부분 한번 확인 부탁드리며 검증 시 확인한 API return data도 같이 첨부해주시면
확인하는데 더 도움이될 것 같습니다~!

2023-02-25 16:19 UTC, NaayoungKwon commented on core/src/main/resources/application-core.yml
> +    host: localhost
그 아마 redis랑 server 랑 둘다 docker container면 localhost로 설정하면 그 각자 container안에서 localhost가 같혀있어요.

https://yoo11052.tistory.com/143

2023-02-25 16:19 UTC, NaayoungKwon commented on .github/workflows/API_CD.yml
> +            docker run --name redis -p 6379:6379 -d redis
이렇게 하면 재 배포될 때 마다 재 실행되는지 잘 모르겠는데.. 서버 외부 파일이랑 연동시켜둬야하지 않을까요?!

2023-02-25 16:19 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
> +            "LEFT JOIN transaction AS t ON t.vacation_id = (SELECT id FROM transaction AS t2 WHERE t2.vacation_id = ? ORDER BY created_at DESC LIMIT 1) " +
여기 subquery 사용한 이유가 따로 있나요?? 하나만 가져오는 용도이면 안써도될 것 같아서 아래 query 처럼 해도될 것 같은데요
```sql
SELECT
    pic.url as pictureUrl,
    v.title as title,
    t.price as currentPrice,
    price.standard_price as startPrice
    FROM vacation AS v
    LEFT JOIN (SELECT p2.id, p2.standard_price, p2.vacation_id FROM price_info AS p2 WHERE p2.vacation_id = ? ORDER BY p2.created_at DESC LIMIT 1) as price ON price.vacation_id = v.id
    LEFT JOIN (SELECT pic2.id, pic2.url, pic2.cahoots_id FROM picture AS pic2 WHERE pic2.cahoots_id = ? ORDER BY pic2.created_at DESC LIMIT 1) as pic ON pic.cahoots_id = v.id
    LEFT JOIN (SELECT t2.id, t2.price, t2.vacation_id FROM transaction AS t2 WHERE t2.vacation_id = ? ORDER BY created_at DESC LIMIT 1) as t ON t.vacation_id = v.id
    WHERE v.id = ?

```

근데 그 원래 코드의 쿼리는 id=1로 주고 실행하면 current_price가 null이고

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/34162358/221367624-ba9de6eb-ba12-421e-b3b8-9bec40638506.png">

제가 다시 작성한 query는 current_price가 나오는데요. 확인 한번 부탁드립니다.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/34162358/221367657-8ded409d-24dd-44a2-84b8-34eaf15181db.png">

2023-02-26 08:20 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
> +            "LEFT JOIN transaction AS t ON t.vacation_id = (SELECT id FROM transaction AS t2 WHERE t2.vacation_id = ? ORDER BY created_at DESC LIMIT 1) " +
요청하신 데이터에 대하여 잘 받아오게 수정하였고 궁금한 점은 LEFT JOIN에서 subquery 하는거랑 ON = subquery 하는거랑 어떤 차이점이 존재하나요? 그리고 시간의 순서를 결정해서 나열하는 것보다 Primary Key의 최대값을 조회하는 것이 더 빠르다고 해서 현재 해당 쿼리를 primary key의 단일값을 가져오는 것으로 수정하였습니다.

2023-02-26 09:10 UTC, CEOJINSUNG commented on .github/workflows/API_CD.yml
> +            docker run --name redis -p 6379:6379 -d redis
재실행되기는 하는데 빼먹은게 서버 상에서 api-server와 redis 연결할 bridge 가 없어서 생성해줘야 될거 같아요

2023-02-26 13:38 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
> +            "LEFT JOIN transaction AS t ON t.vacation_id = (SELECT id FROM transaction AS t2 WHERE t2.vacation_id = ? ORDER BY created_at DESC LIMIT 1) " +
LEFT JOIN price_info AS price ON price.id = (SELECT p2.id FROM price_info AS p2 WHERE p2.vacation_id = ? ORDER BY p2.created_at DESC LIMIT 1)
하나로 예를 들면 지금 서브쿼리로 검색을 한 다음 다시 전체 price_info table에서 해당 id를 검색하는 연산이 또 들어가게 되니까 내부적으로 검색을 한번 더 한다고 생각했어요.

지금 데이터가 얼마 없는 상태에서 두 구문의 실행 속도를 비교했을 땐 얼마 차이가 없고 indexing이 되어있으니 MySQL에서 알아서 optimize해줄거라고 생각하니 크게 고려할 사항은 아닌 것 같네요.

2023-02-26 13:43 UTC, NaayoungKwon approved these changes
고생하셨습니다. 스프린트때 이야기한 network 설정은 제가 해둘건데 혹시 또 모르니 IAM 으로 서버 확인할 수 있게 계정 알려주시면 등록하겠습니다.

2023-02-26 13:56 UTC, merged