Feat/#71 마켓 상세 정보 가져오기
Eagle2gle/wealth-marble-backend pull request #72
Opened 2023-02-07 13:37 UTC by CEOJINSUNG

## 💬 Issue Number

> closes #71

## 🤷‍♂️ Description

> 작업 내용에 대한 설명

- [] : 체크리스트
- [] : 체크리스트
- [] : 체크리스트

## 📋 Check List

> PR 전 체크해주세요.

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] PR 내용이 정상 동작한다는 것을 보증하는 **테스트**를 추가하였는가?

2023-02-07 14:54 UTC, NaayoungKwon requested changes
고생하셨습니다! 코멘트 단 부분 수정가능한지 확인 부탁드립니다.

2023-02-07 14:54 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +            String picture = pictureRepository.findUrlsByCahootsId(vacationId).get(0);
마켓 상세 정보 내 정보 탭에서 사진 여러개를 가져오는 것 같아요

2023-02-07 14:54 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +                .collect(Collectors.toList());
관심 상품 몇명이 했는지 카운팅 용이면 id들을 다 전달하지 않고 count만 전달해도될 것 같아요.

2023-02-08 04:27 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +                .collect(Collectors.toList());
아 이거는 프론트 상에 리스트를 보내면 존재 여부로 화면을 처리할 수 있을 거 같아 진행을 하게 되었어요

2023-02-08 04:27 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +            String picture = pictureRepository.findUrlsByCahootsId(vacationId).get(0);
!? 아 여러 개인가요?

2023-02-08 04:28 UTC, merged

2023-02-08 10:49 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +            String picture = pictureRepository.findUrlsByCahootsId(vacationId).get(0);
네! 사진 여러개라

2023-02-08 11:01 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
> +                .collect(Collectors.toList());
아아 id들 중에서 현재 사용자 id가 있는지를 확인한다는거죠??