Feat/#75 마켓에서 차트 데이터를 가져오는 API
Eagle2gle/wealth-marble-backend pull request #76
Opened 2023-02-08 13:37 UTC by CEOJINSUNG

## 💬 Issue Number

> closes #75

## 🤷‍♂️ Description

> 작업 내용에 대한 설명

- [] : 체크리스트
- [] : 체크리스트
- [] : 체크리스트

## 📋 Check List

> PR 전 체크해주세요.

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] PR 내용이 정상 동작한다는 것을 보증하는 **테스트**를 추가하였는가?

2023-02-08 13:56 UTC, NaayoungKwon requested changes
고생하셨습니다!
하나의 컨트롤러의 도메인은 다음처럼 상단에서 맵핑되도록 하면 좋을 것 같아 코멘트 남겼으니 수정하고 커밋 푸시해주시면 제가 다시 승인할게요~
`@RequestMapping("/api/interests")`

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +    @GetMapping("/price/info/chart/{vacationId}")
여기는 mapping 정보 restcontroller에서 /api/price/info 에서 /api로 바꾸셨나요?

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +            vacationId, new ChartRequestDto(startDate, endDate)
chartRequestDto에 builder가 적용되어있던데 new말고 builder 활용해도 좋을 것 같아요~

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
> +    @GetMapping("/interests/me/interest")
"/interests/me" 이까지만 해도 괜찮지않나요?ㅎㅎ

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
> +@RequestMapping("/api")
여기도 /api/interests 까지가 겹쳐서 위에서 이까지 정의해주면 될 것 같아요.

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/transaction/controller/TransactionController.java
> +    @GetMapping("/transactions/me")
transaction도 mapping 확인 해주세요!

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/controller/MarketController.java
> +    @GetMapping("/markets/{vacationId}")
여기도요 ㅎㅎ

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/vacation/dto/CreateCahootsDto.java
> +                .description(getDescription())
세상에 오타가 ㄷㄷ 감사합니다.

2023-02-08 13:56 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/common/QueryStringArgResolver.java
> +}
여긴 어떤 역할을 하나요?

2023-02-10 11:27 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +    @GetMapping("/price/info/chart/{vacationId}")
저희 회의 때 /api/auth 로 security 설정을 확인하기 위해 해당 url mapping을 바꾸게 되었어요

2023-02-10 11:28 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +            vacationId, new ChartRequestDto(startDate, endDate)
해당 코드에서 2개의 인자밖에 존재하지 않아 new 로 확인하게 되었습니다.

2023-02-10 11:29 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/common/QueryStringArgResolver.java
> +}
해당 쿼리Resolver는 추후 있을 RequestParam 여러개를 Object로 받을 수 있게 변화하는 Anotation입니다.

2023-02-10 11:30 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
> +    @GetMapping("/interests/me/interest")
단순히 me로 하면 겹칠 때 에러가 나서 초기에 설정을 저렇게 했었습니다

2023-02-10 13:35 UTC, NaayoungKwon commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +    @GetMapping("/price/info/chart/{vacationId}")
아아아 저는 그 controller class를 두가지로 두면 될 것 같다고 생각했어요.
security 있는거랑 없는거랑 나눠서요

2023-02-10 13:42 UTC, NaayoungKwon approved these changes
고생하셨습니다!

2023-02-10 13:46 UTC, CEOJINSUNG commented on api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
> +    @GetMapping("/price/info/chart/{vacationId}")
auth 인지 아닌지, 특정 서비스 인지 아닌지 관심사 분리가 제일 어려운거 같아요

2023-02-10 13:46 UTC, merged